GET http://localhost:8080/api/songs

###

POST http://localhost:8080/api/songs
Content-Type: application/json

{
  "name": "FIFA 10",
  "artist": "2",
  "producer": "Electronic Arts",
  "length": "Xbox 360",
  "releasedate": "2009-09-25",
  "multiplayer": "true"
}

###

GET http://localhost:8080/api/songs/9

###

GET http://localhost:8080/api/songs/4

###

PUT http://localhost:8080/api/songs/6
Content-Type: application/json

{
  "releasedate": "2015-10-10",
  "multiplayer": "false"
}

###

GET http://localhost:8080/api/songs/5

###

DELETE http://localhost:8080/api/songs/6

###

GET http://localhost:8080/api/songs

###

GET http://localhost:8080/api/artist

###

GET http://localhost:8080/api/artist/3/songs

###

POST http://localhost:8080/api/artist
Content-Type: application/json

{
  "name": "NBA 2K",
  "genre": "Sports",
  "minAge": "3"
}

###

GET http://localhost:8080/api/artist/3

###

PUT http://localhost:8080/api/artist/10
Content-Type: application/json

{
  "minAge": "7"
}

###

GET http://localhost:8080/api/artist/9/songs

###

GET http://localhost:8080/api/artist/3/songs

###

DELETE http://localhost:8080/api/artist/2

###

GET http://localhost:8080/api/artist

###

GET http://localhost:8080/api/songs

###