GET http://localhost:8081/api/artist

###

GET http://localhost:8081/api/artist/2

###

POST http://localhost:8081/api/artist
Content-Type: application/json

{
  "name": "NBA 2K",
  "genre": "Sports",
  "minAge": "3"
}

###

PUT http://localhost:8081/api/artist/10
Content-Type: application/json

{
  "minAge": "7"
}

###

GET http://localhost:8081/api/artist/10

###

GET http://localhost:8081/api/artist/10/songs

###

DELETE http://localhost:8081/api/artist/3

###